version: '2'
services:
  postgres:
    image: "mdillon/postgis"
    volumes:
        - ./containers/database/kai_db.sql:/docker-entrypoint-initdb.d/kai_db.sql
    container_name: "postgres"
    ports:
      - "58008:5432"
  app:
    container_name: app
    build: containers/app
    volumes:
        - ./containers/app/src:/var/www/app/src
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/kai_db
    ports:
      - "8000:5000"
